server:
  port: 8002 #设置端口为80可以访问时不用输入端口号

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    #表示是否将自己注册进Eurekaserver就认为true.
    register-with-eureka: true
    #是否从Eurekaserver抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #集群版
      #defaultZone: http://eureka7002.com:7001/eureka,http://eureka7002.com:7002/eureka

